#!/usr/bin/env python3
"""
sync-scripts.py — Quarto pre-render hook
Reads js/main.js and writes _partials/scripts.html so they never drift.
Run automatically by Quarto before every render.
"""
from pathlib import Path

src  = Path("js/main.js").read_text()
html = f"""<!-- AUTO-GENERATED — do not edit directly.
     Source of truth: js/main.js
     Regenerated by sync-scripts.py on every quarto render. -->
<script>
{src}
</script>
"""
Path("_partials/scripts.html").write_text(html)
print("sync-scripts.py: scripts.html regenerated from js/main.js")
